### ISSUE TITLE
we need open positions table

### ISSUE THREAD

**Issue by secwang** [dusktrades/ftx-cli#39]
feature request

**Comment by dusktrades** [comment]
Thanks for your suggestion; orders and positions are on the TODO and will feature in an upcoming release!

**Comment by meckin** [comment]
Great, I was looking for the same thing. Seems like the most important feature. If I had some time to hack on this I would, maybe next month. Thanks for the project.

**Comment by dusktrades** [comment]
As an aside, the 'most important feature' title changes frequently because the scope of the project is growing quickly with demand.

What started as a hacky script to auto-compound lending offers, then added advanced trading functionality, which gave rise to the [`wallet`](https://github.com/dusktrades/ftx-cli/tree/master/docs/topics/accounts#-wallet) command because 'how can you trade without seeing your balances?', which now gives rise to orders and positions because 'why is there a command for \<older feature\> but not \<newly important feature\>?'. The scope of the project, and thus expectations of what it 'should' be able to do, grew drastically with the recent addition of trading.

I hope that makes sense. We will get there. 🙂

**Comment by pamelia** [comment]
positions before orders please :)

**Comment by secwang** [comment]
> As an aside, the 'most important feature' title changes frequently because the scope of the project is growing quickly with demand.
> 
> What started as a hacky script to auto-compound lending offers, then added advanced trading functionality, which gave rise to the [`wallet`](https://github.com/dusktrades/ftx-cli/tree/master/docs/topics/accounts#-wallet) command because 'how can you trade without seeing your balances?', which now gives rise to orders and positions because 'why is there a command for <older feature> but not <newly important feature>?'. The scope of the project, and thus expectations of what it 'should' be able to do, grew drastically with the recent addition of trading.
> 
> I hope that makes sense. We will get there. 🙂

Yes.We will get there.

**Comment by dusktrades** [comment]
The [`positions`](https://github.com/dusktrades/ftx-cli/tree/master/docs/topics/trading#-positions) command has been released with FTX CLI v2.3.0!

Please run `npm install -g ftx-cli` to update.

I will close this issue now. Feel free to create a new issue if you face any problems or have more suggestions.
